name: FalloutPlugin
main: io.github.jtagscherer.falloutplugin.FalloutPlugin
version: 0.0.1
author: jtagscherer
commands:
  fallout:
    description: Start and stop the Fallout plugin.
    usage: /fallout [start/stop]
