name: FalloutPlugin
main: io.github.jtagscherer.falloutplugin.FalloutPlugin
version: 0.0.2
api-version: 1.20
author: jtagscherer
commands:
  fallout:
    description: Start and stop the Fallout plugin.
    usage: /fallout [start graceperiod/stop]
